// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ons.proto

package ons_pb2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// string replacement;
// extended properties
type Record_RecordState int32

const (
	Record_RECORD_INACTIVE Record_RecordState = 0
	Record_RECORD_ACTIVE   Record_RecordState = 1
)

var Record_RecordState_name = map[int32]string{
	0: "RECORD_INACTIVE",
	1: "RECORD_ACTIVE",
}
var Record_RecordState_value = map[string]int32{
	"RECORD_INACTIVE": 0,
	"RECORD_ACTIVE":   1,
}

func (x Record_RecordState) String() string {
	return proto.EnumName(Record_RecordState_name, int32(x))
}
func (Record_RecordState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ons_6c9d57a7a195b028, []int{1, 0}
}

type GS1CodeData_GS1CodeState int32

const (
	GS1CodeData_GS1CODE_NONE     GS1CodeData_GS1CodeState = 0
	GS1CodeData_GS1CODE_INACTIVE GS1CodeData_GS1CodeState = 1
	GS1CodeData_GS1CODE_ACTIVE   GS1CodeData_GS1CodeState = 2
)

var GS1CodeData_GS1CodeState_name = map[int32]string{
	0: "GS1CODE_NONE",
	1: "GS1CODE_INACTIVE",
	2: "GS1CODE_ACTIVE",
}
var GS1CodeData_GS1CodeState_value = map[string]int32{
	"GS1CODE_NONE":     0,
	"GS1CODE_INACTIVE": 1,
	"GS1CODE_ACTIVE":   2,
}

func (x GS1CodeData_GS1CodeState) String() string {
	return proto.EnumName(GS1CodeData_GS1CodeState_name, int32(x))
}
func (GS1CodeData_GS1CodeState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ons_6c9d57a7a195b028, []int{2, 0}
}

type SendONSTransactionPayload_ONSTransactionType int32

const (
	SendONSTransactionPayload_REGISTER_GS1CODE       SendONSTransactionPayload_ONSTransactionType = 0
	SendONSTransactionPayload_DEREGISTER_GS1CODE     SendONSTransactionPayload_ONSTransactionType = 1
	SendONSTransactionPayload_ADD_RECORD             SendONSTransactionPayload_ONSTransactionType = 2
	SendONSTransactionPayload_REMOVE_RECORD          SendONSTransactionPayload_ONSTransactionType = 3
	SendONSTransactionPayload_REGISTER_SERVICETYPE   SendONSTransactionPayload_ONSTransactionType = 4
	SendONSTransactionPayload_DEREGISTER_SERVICETYPE SendONSTransactionPayload_ONSTransactionType = 5
	SendONSTransactionPayload_CHANGE_GS1CODE_STATE   SendONSTransactionPayload_ONSTransactionType = 6
	SendONSTransactionPayload_CHANGE_RECORD_STATE    SendONSTransactionPayload_ONSTransactionType = 7
)

var SendONSTransactionPayload_ONSTransactionType_name = map[int32]string{
	0: "REGISTER_GS1CODE",
	1: "DEREGISTER_GS1CODE",
	2: "ADD_RECORD",
	3: "REMOVE_RECORD",
	4: "REGISTER_SERVICETYPE",
	5: "DEREGISTER_SERVICETYPE",
	6: "CHANGE_GS1CODE_STATE",
	7: "CHANGE_RECORD_STATE",
}
var SendONSTransactionPayload_ONSTransactionType_value = map[string]int32{
	"REGISTER_GS1CODE":       0,
	"DEREGISTER_GS1CODE":     1,
	"ADD_RECORD":             2,
	"REMOVE_RECORD":          3,
	"REGISTER_SERVICETYPE":   4,
	"DEREGISTER_SERVICETYPE": 5,
	"CHANGE_GS1CODE_STATE":   6,
	"CHANGE_RECORD_STATE":    7,
}

func (x SendONSTransactionPayload_ONSTransactionType) String() string {
	return proto.EnumName(SendONSTransactionPayload_ONSTransactionType_name, int32(x))
}
func (SendONSTransactionPayload_ONSTransactionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ons_6c9d57a7a195b028, []int{3, 0}
}

type ServiceType struct {
	// service_type_address는 transaction process 내부적으로 생성된다.
	// client에서 저장한 service_type_address는 무시된다.
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	//
	// fields에는 일반적으로 "string(key) : string(value)"의 key value를 저장한다.
	// 만약, string(key) : json (value)을 저장이 필요한 경우
	// types에 key_name(fields의 key) : type name(fields의 value, 예를 들어 "json")으로
	// types map에 저장한다.
	Fields []*ServiceType_ServiceTypeField `protobuf:"bytes,2,rep,name=fields" json:"fields,omitempty"`
	Types  []*ServiceType_ServiceTypeField `protobuf:"bytes,3,rep,name=types" json:"types,omitempty"`
	// service type을 등록하는 address. (service type 제공자의 public key)
	// client에서 저장한 public key는 무시되고 transaction을 전송할 때 사용된
	// public key를 사용한다.
	Provider             string   `protobuf:"bytes,4,opt,name=provider" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceType) Reset()         { *m = ServiceType{} }
func (m *ServiceType) String() string { return proto.CompactTextString(m) }
func (*ServiceType) ProtoMessage()    {}
func (*ServiceType) Descriptor() ([]byte, []int) {
	return fileDescriptor_ons_6c9d57a7a195b028, []int{0}
}
func (m *ServiceType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceType.Unmarshal(m, b)
}
func (m *ServiceType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceType.Marshal(b, m, deterministic)
}
func (dst *ServiceType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceType.Merge(dst, src)
}
func (m *ServiceType) XXX_Size() int {
	return xxx_messageInfo_ServiceType.Size(m)
}
func (m *ServiceType) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceType.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceType proto.InternalMessageInfo

func (m *ServiceType) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ServiceType) GetFields() []*ServiceType_ServiceTypeField {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ServiceType) GetTypes() []*ServiceType_ServiceTypeField {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *ServiceType) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

type ServiceType_ServiceTypeField struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceType_ServiceTypeField) Reset()         { *m = ServiceType_ServiceTypeField{} }
func (m *ServiceType_ServiceTypeField) String() string { return proto.CompactTextString(m) }
func (*ServiceType_ServiceTypeField) ProtoMessage()    {}
func (*ServiceType_ServiceTypeField) Descriptor() ([]byte, []int) {
	return fileDescriptor_ons_6c9d57a7a195b028, []int{0, 0}
}
func (m *ServiceType_ServiceTypeField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceType_ServiceTypeField.Unmarshal(m, b)
}
func (m *ServiceType_ServiceTypeField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceType_ServiceTypeField.Marshal(b, m, deterministic)
}
func (dst *ServiceType_ServiceTypeField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceType_ServiceTypeField.Merge(dst, src)
}
func (m *ServiceType_ServiceTypeField) XXX_Size() int {
	return xxx_messageInfo_ServiceType_ServiceTypeField.Size(m)
}
func (m *ServiceType_ServiceTypeField) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceType_ServiceTypeField.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceType_ServiceTypeField proto.InternalMessageInfo

func (m *ServiceType_ServiceTypeField) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ServiceType_ServiceTypeField) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Record struct {
	// uint32 order;
	// uint32 pref;
	// flags will be rune type in golang.
	Flags   int32              `protobuf:"varint,1,opt,name=flags" json:"flags,omitempty"`
	Service string             `protobuf:"bytes,2,opt,name=service" json:"service,omitempty"`
	Regexp  string             `protobuf:"bytes,3,opt,name=regexp" json:"regexp,omitempty"`
	State   Record_RecordState `protobuf:"varint,4,opt,name=state,enum=Record_RecordState" json:"state,omitempty"`
	// record를 등록한 address. (service 제공자)
	Provider             string   `protobuf:"bytes,5,opt,name=provider" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_ons_6c9d57a7a195b028, []int{1}
}
func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (dst *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(dst, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetFlags() int32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *Record) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Record) GetRegexp() string {
	if m != nil {
		return m.Regexp
	}
	return ""
}

func (m *Record) GetState() Record_RecordState {
	if m != nil {
		return m.State
	}
	return Record_RECORD_INACTIVE
}

func (m *Record) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

type GS1CodeData struct {
	// unique gs1 code string
	Gs1Code string `protobuf:"bytes,1,opt,name=gs1_code,json=gs1Code" json:"gs1_code,omitempty"`
	// unique onwer public key
	OwnerId string `protobuf:"bytes,2,opt,name=owner_id,json=ownerId" json:"owner_id,omitempty"`
	// records will be slice.
	Records []*Record `protobuf:"bytes,3,rep,name=records" json:"records,omitempty"`
	// 0: not belong to anyone, 1 : inactive state, 2: active state
	State                GS1CodeData_GS1CodeState `protobuf:"varint,4,opt,name=state,enum=GS1CodeData_GS1CodeState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GS1CodeData) Reset()         { *m = GS1CodeData{} }
func (m *GS1CodeData) String() string { return proto.CompactTextString(m) }
func (*GS1CodeData) ProtoMessage()    {}
func (*GS1CodeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ons_6c9d57a7a195b028, []int{2}
}
func (m *GS1CodeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GS1CodeData.Unmarshal(m, b)
}
func (m *GS1CodeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GS1CodeData.Marshal(b, m, deterministic)
}
func (dst *GS1CodeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GS1CodeData.Merge(dst, src)
}
func (m *GS1CodeData) XXX_Size() int {
	return xxx_messageInfo_GS1CodeData.Size(m)
}
func (m *GS1CodeData) XXX_DiscardUnknown() {
	xxx_messageInfo_GS1CodeData.DiscardUnknown(m)
}

var xxx_messageInfo_GS1CodeData proto.InternalMessageInfo

func (m *GS1CodeData) GetGs1Code() string {
	if m != nil {
		return m.Gs1Code
	}
	return ""
}

func (m *GS1CodeData) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *GS1CodeData) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

func (m *GS1CodeData) GetState() GS1CodeData_GS1CodeState {
	if m != nil {
		return m.State
	}
	return GS1CodeData_GS1CODE_NONE
}

type SendONSTransactionPayload struct {
	TransactionType       SendONSTransactionPayload_ONSTransactionType                    `protobuf:"varint,1,opt,name=transaction_type,json=transactionType,enum=SendONSTransactionPayload_ONSTransactionType" json:"transaction_type,omitempty"`
	RegisterGs1Code       *SendONSTransactionPayload_RegisterGS1CodeTransactionData       `protobuf:"bytes,2,opt,name=register_gs1_code,json=registerGs1Code" json:"register_gs1_code,omitempty"`
	DeregisterGs1Code     *SendONSTransactionPayload_DeregisterGS1CodeTransactionData     `protobuf:"bytes,3,opt,name=deregister_gs1_code,json=deregisterGs1Code" json:"deregister_gs1_code,omitempty"`
	AddRecord             *SendONSTransactionPayload_AddRecordTransactionData             `protobuf:"bytes,4,opt,name=add_record,json=addRecord" json:"add_record,omitempty"`
	RemoveRecord          *SendONSTransactionPayload_RemoveRecordTransactionData          `protobuf:"bytes,5,opt,name=remove_record,json=removeRecord" json:"remove_record,omitempty"`
	RegisterServiceType   *SendONSTransactionPayload_RegisterServiceTypeTransactionData   `protobuf:"bytes,6,opt,name=register_service_type,json=registerServiceType" json:"register_service_type,omitempty"`
	DeregisterServiceType *SendONSTransactionPayload_DeregisterServiceTypeTransactionData `protobuf:"bytes,7,opt,name=deregister_service_type,json=deregisterServiceType" json:"deregister_service_type,omitempty"`
	ChangeGs1CodeState    *SendONSTransactionPayload_ChangeGS1CodeStateTransactionData    `protobuf:"bytes,8,opt,name=change_gs1_code_state,json=changeGs1CodeState" json:"change_gs1_code_state,omitempty"`
	ChangeRecordState     *SendONSTransactionPayload_ChangeRecordStateTransactionData     `protobuf:"bytes,9,opt,name=change_record_state,json=changeRecordState" json:"change_record_state,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                                                        `json:"-"`
	XXX_unrecognized      []byte                                                          `json:"-"`
	XXX_sizecache         int32                                                           `json:"-"`
}

func (m *SendONSTransactionPayload) Reset()         { *m = SendONSTransactionPayload{} }
func (m *SendONSTransactionPayload) String() string { return proto.CompactTextString(m) }
func (*SendONSTransactionPayload) ProtoMessage()    {}
func (*SendONSTransactionPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_ons_6c9d57a7a195b028, []int{3}
}
func (m *SendONSTransactionPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendONSTransactionPayload.Unmarshal(m, b)
}
func (m *SendONSTransactionPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendONSTransactionPayload.Marshal(b, m, deterministic)
}
func (dst *SendONSTransactionPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendONSTransactionPayload.Merge(dst, src)
}
func (m *SendONSTransactionPayload) XXX_Size() int {
	return xxx_messageInfo_SendONSTransactionPayload.Size(m)
}
func (m *SendONSTransactionPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_SendONSTransactionPayload.DiscardUnknown(m)
}

var xxx_messageInfo_SendONSTransactionPayload proto.InternalMessageInfo

func (m *SendONSTransactionPayload) GetTransactionType() SendONSTransactionPayload_ONSTransactionType {
	if m != nil {
		return m.TransactionType
	}
	return SendONSTransactionPayload_REGISTER_GS1CODE
}

func (m *SendONSTransactionPayload) GetRegisterGs1Code() *SendONSTransactionPayload_RegisterGS1CodeTransactionData {
	if m != nil {
		return m.RegisterGs1Code
	}
	return nil
}

func (m *SendONSTransactionPayload) GetDeregisterGs1Code() *SendONSTransactionPayload_DeregisterGS1CodeTransactionData {
	if m != nil {
		return m.DeregisterGs1Code
	}
	return nil
}

func (m *SendONSTransactionPayload) GetAddRecord() *SendONSTransactionPayload_AddRecordTransactionData {
	if m != nil {
		return m.AddRecord
	}
	return nil
}

func (m *SendONSTransactionPayload) GetRemoveRecord() *SendONSTransactionPayload_RemoveRecordTransactionData {
	if m != nil {
		return m.RemoveRecord
	}
	return nil
}

func (m *SendONSTransactionPayload) GetRegisterServiceType() *SendONSTransactionPayload_RegisterServiceTypeTransactionData {
	if m != nil {
		return m.RegisterServiceType
	}
	return nil
}

func (m *SendONSTransactionPayload) GetDeregisterServiceType() *SendONSTransactionPayload_DeregisterServiceTypeTransactionData {
	if m != nil {
		return m.DeregisterServiceType
	}
	return nil
}

func (m *SendONSTransactionPayload) GetChangeGs1CodeState() *SendONSTransactionPayload_ChangeGS1CodeStateTransactionData {
	if m != nil {
		return m.ChangeGs1CodeState
	}
	return nil
}

func (m *SendONSTransactionPayload) GetChangeRecordState() *SendONSTransactionPayload_ChangeRecordStateTransactionData {
	if m != nil {
		return m.ChangeRecordState
	}
	return nil
}

type SendONSTransactionPayload_RegisterGS1CodeTransactionData struct {
	Gs1Code              string   `protobuf:"bytes,1,opt,name=gs1_code,json=gs1Code" json:"gs1_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendONSTransactionPayload_RegisterGS1CodeTransactionData) Reset() {
	*m = SendONSTransactionPayload_RegisterGS1CodeTransactionData{}
}
func (m *SendONSTransactionPayload_RegisterGS1CodeTransactionData) String() string {
	return proto.CompactTextString(m)
}
func (*SendONSTransactionPayload_RegisterGS1CodeTransactionData) ProtoMessage() {}
func (*SendONSTransactionPayload_RegisterGS1CodeTransactionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ons_6c9d57a7a195b028, []int{3, 0}
}
func (m *SendONSTransactionPayload_RegisterGS1CodeTransactionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendONSTransactionPayload_RegisterGS1CodeTransactionData.Unmarshal(m, b)
}
func (m *SendONSTransactionPayload_RegisterGS1CodeTransactionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendONSTransactionPayload_RegisterGS1CodeTransactionData.Marshal(b, m, deterministic)
}
func (dst *SendONSTransactionPayload_RegisterGS1CodeTransactionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendONSTransactionPayload_RegisterGS1CodeTransactionData.Merge(dst, src)
}
func (m *SendONSTransactionPayload_RegisterGS1CodeTransactionData) XXX_Size() int {
	return xxx_messageInfo_SendONSTransactionPayload_RegisterGS1CodeTransactionData.Size(m)
}
func (m *SendONSTransactionPayload_RegisterGS1CodeTransactionData) XXX_DiscardUnknown() {
	xxx_messageInfo_SendONSTransactionPayload_RegisterGS1CodeTransactionData.DiscardUnknown(m)
}

var xxx_messageInfo_SendONSTransactionPayload_RegisterGS1CodeTransactionData proto.InternalMessageInfo

func (m *SendONSTransactionPayload_RegisterGS1CodeTransactionData) GetGs1Code() string {
	if m != nil {
		return m.Gs1Code
	}
	return ""
}

type SendONSTransactionPayload_DeregisterGS1CodeTransactionData struct {
	Gs1Code              string   `protobuf:"bytes,1,opt,name=gs1_code,json=gs1Code" json:"gs1_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendONSTransactionPayload_DeregisterGS1CodeTransactionData) Reset() {
	*m = SendONSTransactionPayload_DeregisterGS1CodeTransactionData{}
}
func (m *SendONSTransactionPayload_DeregisterGS1CodeTransactionData) String() string {
	return proto.CompactTextString(m)
}
func (*SendONSTransactionPayload_DeregisterGS1CodeTransactionData) ProtoMessage() {}
func (*SendONSTransactionPayload_DeregisterGS1CodeTransactionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ons_6c9d57a7a195b028, []int{3, 1}
}
func (m *SendONSTransactionPayload_DeregisterGS1CodeTransactionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendONSTransactionPayload_DeregisterGS1CodeTransactionData.Unmarshal(m, b)
}
func (m *SendONSTransactionPayload_DeregisterGS1CodeTransactionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendONSTransactionPayload_DeregisterGS1CodeTransactionData.Marshal(b, m, deterministic)
}
func (dst *SendONSTransactionPayload_DeregisterGS1CodeTransactionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendONSTransactionPayload_DeregisterGS1CodeTransactionData.Merge(dst, src)
}
func (m *SendONSTransactionPayload_DeregisterGS1CodeTransactionData) XXX_Size() int {
	return xxx_messageInfo_SendONSTransactionPayload_DeregisterGS1CodeTransactionData.Size(m)
}
func (m *SendONSTransactionPayload_DeregisterGS1CodeTransactionData) XXX_DiscardUnknown() {
	xxx_messageInfo_SendONSTransactionPayload_DeregisterGS1CodeTransactionData.DiscardUnknown(m)
}

var xxx_messageInfo_SendONSTransactionPayload_DeregisterGS1CodeTransactionData proto.InternalMessageInfo

func (m *SendONSTransactionPayload_DeregisterGS1CodeTransactionData) GetGs1Code() string {
	if m != nil {
		return m.Gs1Code
	}
	return ""
}

type SendONSTransactionPayload_RecordTranactionData struct {
	Flags                int32    `protobuf:"varint,1,opt,name=flags" json:"flags,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service" json:"service,omitempty"`
	Regexp               string   `protobuf:"bytes,3,opt,name=regexp" json:"regexp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendONSTransactionPayload_RecordTranactionData) Reset() {
	*m = SendONSTransactionPayload_RecordTranactionData{}
}
func (m *SendONSTransactionPayload_RecordTranactionData) String() string {
	return proto.CompactTextString(m)
}
func (*SendONSTransactionPayload_RecordTranactionData) ProtoMessage() {}
func (*SendONSTransactionPayload_RecordTranactionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ons_6c9d57a7a195b028, []int{3, 2}
}
func (m *SendONSTransactionPayload_RecordTranactionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendONSTransactionPayload_RecordTranactionData.Unmarshal(m, b)
}
func (m *SendONSTransactionPayload_RecordTranactionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendONSTransactionPayload_RecordTranactionData.Marshal(b, m, deterministic)
}
func (dst *SendONSTransactionPayload_RecordTranactionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendONSTransactionPayload_RecordTranactionData.Merge(dst, src)
}
func (m *SendONSTransactionPayload_RecordTranactionData) XXX_Size() int {
	return xxx_messageInfo_SendONSTransactionPayload_RecordTranactionData.Size(m)
}
func (m *SendONSTransactionPayload_RecordTranactionData) XXX_DiscardUnknown() {
	xxx_messageInfo_SendONSTransactionPayload_RecordTranactionData.DiscardUnknown(m)
}

var xxx_messageInfo_SendONSTransactionPayload_RecordTranactionData proto.InternalMessageInfo

func (m *SendONSTransactionPayload_RecordTranactionData) GetFlags() int32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *SendONSTransactionPayload_RecordTranactionData) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *SendONSTransactionPayload_RecordTranactionData) GetRegexp() string {
	if m != nil {
		return m.Regexp
	}
	return ""
}

type SendONSTransactionPayload_AddRecordTransactionData struct {
	Gs1Code              string                                          `protobuf:"bytes,1,opt,name=gs1_code,json=gs1Code" json:"gs1_code,omitempty"`
	Record               *SendONSTransactionPayload_RecordTranactionData `protobuf:"bytes,2,opt,name=record" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                        `json:"-"`
	XXX_unrecognized     []byte                                          `json:"-"`
	XXX_sizecache        int32                                           `json:"-"`
}

func (m *SendONSTransactionPayload_AddRecordTransactionData) Reset() {
	*m = SendONSTransactionPayload_AddRecordTransactionData{}
}
func (m *SendONSTransactionPayload_AddRecordTransactionData) String() string {
	return proto.CompactTextString(m)
}
func (*SendONSTransactionPayload_AddRecordTransactionData) ProtoMessage() {}
func (*SendONSTransactionPayload_AddRecordTransactionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ons_6c9d57a7a195b028, []int{3, 3}
}
func (m *SendONSTransactionPayload_AddRecordTransactionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendONSTransactionPayload_AddRecordTransactionData.Unmarshal(m, b)
}
func (m *SendONSTransactionPayload_AddRecordTransactionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendONSTransactionPayload_AddRecordTransactionData.Marshal(b, m, deterministic)
}
func (dst *SendONSTransactionPayload_AddRecordTransactionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendONSTransactionPayload_AddRecordTransactionData.Merge(dst, src)
}
func (m *SendONSTransactionPayload_AddRecordTransactionData) XXX_Size() int {
	return xxx_messageInfo_SendONSTransactionPayload_AddRecordTransactionData.Size(m)
}
func (m *SendONSTransactionPayload_AddRecordTransactionData) XXX_DiscardUnknown() {
	xxx_messageInfo_SendONSTransactionPayload_AddRecordTransactionData.DiscardUnknown(m)
}

var xxx_messageInfo_SendONSTransactionPayload_AddRecordTransactionData proto.InternalMessageInfo

func (m *SendONSTransactionPayload_AddRecordTransactionData) GetGs1Code() string {
	if m != nil {
		return m.Gs1Code
	}
	return ""
}

func (m *SendONSTransactionPayload_AddRecordTransactionData) GetRecord() *SendONSTransactionPayload_RecordTranactionData {
	if m != nil {
		return m.Record
	}
	return nil
}

type SendONSTransactionPayload_RemoveRecordTransactionData struct {
	Gs1Code              string   `protobuf:"bytes,1,opt,name=gs1_code,json=gs1Code" json:"gs1_code,omitempty"`
	Index                uint32   `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendONSTransactionPayload_RemoveRecordTransactionData) Reset() {
	*m = SendONSTransactionPayload_RemoveRecordTransactionData{}
}
func (m *SendONSTransactionPayload_RemoveRecordTransactionData) String() string {
	return proto.CompactTextString(m)
}
func (*SendONSTransactionPayload_RemoveRecordTransactionData) ProtoMessage() {}
func (*SendONSTransactionPayload_RemoveRecordTransactionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ons_6c9d57a7a195b028, []int{3, 4}
}
func (m *SendONSTransactionPayload_RemoveRecordTransactionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendONSTransactionPayload_RemoveRecordTransactionData.Unmarshal(m, b)
}
func (m *SendONSTransactionPayload_RemoveRecordTransactionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendONSTransactionPayload_RemoveRecordTransactionData.Marshal(b, m, deterministic)
}
func (dst *SendONSTransactionPayload_RemoveRecordTransactionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendONSTransactionPayload_RemoveRecordTransactionData.Merge(dst, src)
}
func (m *SendONSTransactionPayload_RemoveRecordTransactionData) XXX_Size() int {
	return xxx_messageInfo_SendONSTransactionPayload_RemoveRecordTransactionData.Size(m)
}
func (m *SendONSTransactionPayload_RemoveRecordTransactionData) XXX_DiscardUnknown() {
	xxx_messageInfo_SendONSTransactionPayload_RemoveRecordTransactionData.DiscardUnknown(m)
}

var xxx_messageInfo_SendONSTransactionPayload_RemoveRecordTransactionData proto.InternalMessageInfo

func (m *SendONSTransactionPayload_RemoveRecordTransactionData) GetGs1Code() string {
	if m != nil {
		return m.Gs1Code
	}
	return ""
}

func (m *SendONSTransactionPayload_RemoveRecordTransactionData) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type SendONSTransactionPayload_RegisterServiceTypeTransactionData struct {
	Address              string       `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	ServiceType          *ServiceType `protobuf:"bytes,2,opt,name=service_type,json=serviceType" json:"service_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SendONSTransactionPayload_RegisterServiceTypeTransactionData) Reset() {
	*m = SendONSTransactionPayload_RegisterServiceTypeTransactionData{}
}
func (m *SendONSTransactionPayload_RegisterServiceTypeTransactionData) String() string {
	return proto.CompactTextString(m)
}
func (*SendONSTransactionPayload_RegisterServiceTypeTransactionData) ProtoMessage() {}
func (*SendONSTransactionPayload_RegisterServiceTypeTransactionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ons_6c9d57a7a195b028, []int{3, 5}
}
func (m *SendONSTransactionPayload_RegisterServiceTypeTransactionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendONSTransactionPayload_RegisterServiceTypeTransactionData.Unmarshal(m, b)
}
func (m *SendONSTransactionPayload_RegisterServiceTypeTransactionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendONSTransactionPayload_RegisterServiceTypeTransactionData.Marshal(b, m, deterministic)
}
func (dst *SendONSTransactionPayload_RegisterServiceTypeTransactionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendONSTransactionPayload_RegisterServiceTypeTransactionData.Merge(dst, src)
}
func (m *SendONSTransactionPayload_RegisterServiceTypeTransactionData) XXX_Size() int {
	return xxx_messageInfo_SendONSTransactionPayload_RegisterServiceTypeTransactionData.Size(m)
}
func (m *SendONSTransactionPayload_RegisterServiceTypeTransactionData) XXX_DiscardUnknown() {
	xxx_messageInfo_SendONSTransactionPayload_RegisterServiceTypeTransactionData.DiscardUnknown(m)
}

var xxx_messageInfo_SendONSTransactionPayload_RegisterServiceTypeTransactionData proto.InternalMessageInfo

func (m *SendONSTransactionPayload_RegisterServiceTypeTransactionData) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SendONSTransactionPayload_RegisterServiceTypeTransactionData) GetServiceType() *ServiceType {
	if m != nil {
		return m.ServiceType
	}
	return nil
}

type SendONSTransactionPayload_DeregisterServiceTypeTransactionData struct {
	Address              string   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendONSTransactionPayload_DeregisterServiceTypeTransactionData) Reset() {
	*m = SendONSTransactionPayload_DeregisterServiceTypeTransactionData{}
}
func (m *SendONSTransactionPayload_DeregisterServiceTypeTransactionData) String() string {
	return proto.CompactTextString(m)
}
func (*SendONSTransactionPayload_DeregisterServiceTypeTransactionData) ProtoMessage() {}
func (*SendONSTransactionPayload_DeregisterServiceTypeTransactionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ons_6c9d57a7a195b028, []int{3, 6}
}
func (m *SendONSTransactionPayload_DeregisterServiceTypeTransactionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendONSTransactionPayload_DeregisterServiceTypeTransactionData.Unmarshal(m, b)
}
func (m *SendONSTransactionPayload_DeregisterServiceTypeTransactionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendONSTransactionPayload_DeregisterServiceTypeTransactionData.Marshal(b, m, deterministic)
}
func (dst *SendONSTransactionPayload_DeregisterServiceTypeTransactionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendONSTransactionPayload_DeregisterServiceTypeTransactionData.Merge(dst, src)
}
func (m *SendONSTransactionPayload_DeregisterServiceTypeTransactionData) XXX_Size() int {
	return xxx_messageInfo_SendONSTransactionPayload_DeregisterServiceTypeTransactionData.Size(m)
}
func (m *SendONSTransactionPayload_DeregisterServiceTypeTransactionData) XXX_DiscardUnknown() {
	xxx_messageInfo_SendONSTransactionPayload_DeregisterServiceTypeTransactionData.DiscardUnknown(m)
}

var xxx_messageInfo_SendONSTransactionPayload_DeregisterServiceTypeTransactionData proto.InternalMessageInfo

func (m *SendONSTransactionPayload_DeregisterServiceTypeTransactionData) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type SendONSTransactionPayload_ChangeGS1CodeStateTransactionData struct {
	Gs1Code              string                   `protobuf:"bytes,1,opt,name=gs1_code,json=gs1Code" json:"gs1_code,omitempty"`
	State                GS1CodeData_GS1CodeState `protobuf:"varint,2,opt,name=state,enum=GS1CodeData_GS1CodeState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SendONSTransactionPayload_ChangeGS1CodeStateTransactionData) Reset() {
	*m = SendONSTransactionPayload_ChangeGS1CodeStateTransactionData{}
}
func (m *SendONSTransactionPayload_ChangeGS1CodeStateTransactionData) String() string {
	return proto.CompactTextString(m)
}
func (*SendONSTransactionPayload_ChangeGS1CodeStateTransactionData) ProtoMessage() {}
func (*SendONSTransactionPayload_ChangeGS1CodeStateTransactionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ons_6c9d57a7a195b028, []int{3, 7}
}
func (m *SendONSTransactionPayload_ChangeGS1CodeStateTransactionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendONSTransactionPayload_ChangeGS1CodeStateTransactionData.Unmarshal(m, b)
}
func (m *SendONSTransactionPayload_ChangeGS1CodeStateTransactionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendONSTransactionPayload_ChangeGS1CodeStateTransactionData.Marshal(b, m, deterministic)
}
func (dst *SendONSTransactionPayload_ChangeGS1CodeStateTransactionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendONSTransactionPayload_ChangeGS1CodeStateTransactionData.Merge(dst, src)
}
func (m *SendONSTransactionPayload_ChangeGS1CodeStateTransactionData) XXX_Size() int {
	return xxx_messageInfo_SendONSTransactionPayload_ChangeGS1CodeStateTransactionData.Size(m)
}
func (m *SendONSTransactionPayload_ChangeGS1CodeStateTransactionData) XXX_DiscardUnknown() {
	xxx_messageInfo_SendONSTransactionPayload_ChangeGS1CodeStateTransactionData.DiscardUnknown(m)
}

var xxx_messageInfo_SendONSTransactionPayload_ChangeGS1CodeStateTransactionData proto.InternalMessageInfo

func (m *SendONSTransactionPayload_ChangeGS1CodeStateTransactionData) GetGs1Code() string {
	if m != nil {
		return m.Gs1Code
	}
	return ""
}

func (m *SendONSTransactionPayload_ChangeGS1CodeStateTransactionData) GetState() GS1CodeData_GS1CodeState {
	if m != nil {
		return m.State
	}
	return GS1CodeData_GS1CODE_NONE
}

type SendONSTransactionPayload_ChangeRecordStateTransactionData struct {
	Gs1Code string `protobuf:"bytes,1,opt,name=gs1_code,json=gs1Code" json:"gs1_code,omitempty"`
	// record index
	Index                uint32             `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	State                Record_RecordState `protobuf:"varint,3,opt,name=state,enum=Record_RecordState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SendONSTransactionPayload_ChangeRecordStateTransactionData) Reset() {
	*m = SendONSTransactionPayload_ChangeRecordStateTransactionData{}
}
func (m *SendONSTransactionPayload_ChangeRecordStateTransactionData) String() string {
	return proto.CompactTextString(m)
}
func (*SendONSTransactionPayload_ChangeRecordStateTransactionData) ProtoMessage() {}
func (*SendONSTransactionPayload_ChangeRecordStateTransactionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ons_6c9d57a7a195b028, []int{3, 8}
}
func (m *SendONSTransactionPayload_ChangeRecordStateTransactionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendONSTransactionPayload_ChangeRecordStateTransactionData.Unmarshal(m, b)
}
func (m *SendONSTransactionPayload_ChangeRecordStateTransactionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendONSTransactionPayload_ChangeRecordStateTransactionData.Marshal(b, m, deterministic)
}
func (dst *SendONSTransactionPayload_ChangeRecordStateTransactionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendONSTransactionPayload_ChangeRecordStateTransactionData.Merge(dst, src)
}
func (m *SendONSTransactionPayload_ChangeRecordStateTransactionData) XXX_Size() int {
	return xxx_messageInfo_SendONSTransactionPayload_ChangeRecordStateTransactionData.Size(m)
}
func (m *SendONSTransactionPayload_ChangeRecordStateTransactionData) XXX_DiscardUnknown() {
	xxx_messageInfo_SendONSTransactionPayload_ChangeRecordStateTransactionData.DiscardUnknown(m)
}

var xxx_messageInfo_SendONSTransactionPayload_ChangeRecordStateTransactionData proto.InternalMessageInfo

func (m *SendONSTransactionPayload_ChangeRecordStateTransactionData) GetGs1Code() string {
	if m != nil {
		return m.Gs1Code
	}
	return ""
}

func (m *SendONSTransactionPayload_ChangeRecordStateTransactionData) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *SendONSTransactionPayload_ChangeRecordStateTransactionData) GetState() Record_RecordState {
	if m != nil {
		return m.State
	}
	return Record_RECORD_INACTIVE
}

func init() {
	proto.RegisterType((*ServiceType)(nil), "ServiceType")
	proto.RegisterType((*ServiceType_ServiceTypeField)(nil), "ServiceType.ServiceTypeField")
	proto.RegisterType((*Record)(nil), "Record")
	proto.RegisterType((*GS1CodeData)(nil), "GS1CodeData")
	proto.RegisterType((*SendONSTransactionPayload)(nil), "SendONSTransactionPayload")
	proto.RegisterType((*SendONSTransactionPayload_RegisterGS1CodeTransactionData)(nil), "SendONSTransactionPayload.RegisterGS1CodeTransactionData")
	proto.RegisterType((*SendONSTransactionPayload_DeregisterGS1CodeTransactionData)(nil), "SendONSTransactionPayload.DeregisterGS1CodeTransactionData")
	proto.RegisterType((*SendONSTransactionPayload_RecordTranactionData)(nil), "SendONSTransactionPayload.RecordTranactionData")
	proto.RegisterType((*SendONSTransactionPayload_AddRecordTransactionData)(nil), "SendONSTransactionPayload.AddRecordTransactionData")
	proto.RegisterType((*SendONSTransactionPayload_RemoveRecordTransactionData)(nil), "SendONSTransactionPayload.RemoveRecordTransactionData")
	proto.RegisterType((*SendONSTransactionPayload_RegisterServiceTypeTransactionData)(nil), "SendONSTransactionPayload.RegisterServiceTypeTransactionData")
	proto.RegisterType((*SendONSTransactionPayload_DeregisterServiceTypeTransactionData)(nil), "SendONSTransactionPayload.DeregisterServiceTypeTransactionData")
	proto.RegisterType((*SendONSTransactionPayload_ChangeGS1CodeStateTransactionData)(nil), "SendONSTransactionPayload.ChangeGS1CodeStateTransactionData")
	proto.RegisterType((*SendONSTransactionPayload_ChangeRecordStateTransactionData)(nil), "SendONSTransactionPayload.ChangeRecordStateTransactionData")
	proto.RegisterEnum("Record_RecordState", Record_RecordState_name, Record_RecordState_value)
	proto.RegisterEnum("GS1CodeData_GS1CodeState", GS1CodeData_GS1CodeState_name, GS1CodeData_GS1CodeState_value)
	proto.RegisterEnum("SendONSTransactionPayload_ONSTransactionType", SendONSTransactionPayload_ONSTransactionType_name, SendONSTransactionPayload_ONSTransactionType_value)
}

func init() { proto.RegisterFile("ons.proto", fileDescriptor_ons_6c9d57a7a195b028) }

var fileDescriptor_ons_6c9d57a7a195b028 = []byte{
	// 886 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x5f, 0x8f, 0xda, 0x46,
	0x10, 0x8f, 0x21, 0x86, 0x63, 0xb8, 0x03, 0xdf, 0xc2, 0x5d, 0x7c, 0xae, 0x5a, 0x11, 0xd4, 0x87,
	0xf4, 0xa1, 0x9c, 0xc2, 0x29, 0x95, 0xda, 0x34, 0x6a, 0x29, 0xb8, 0x94, 0x4a, 0x85, 0x68, 0x8d,
	0x4e, 0xfd, 0x23, 0xd5, 0x72, 0xd8, 0x0d, 0x45, 0x47, 0x6d, 0x6a, 0xbb, 0x24, 0xbc, 0xe4, 0x23,
	0xf6, 0x4b, 0x54, 0x7d, 0xea, 0x97, 0xa8, 0xf6, 0x8f, 0xcd, 0x02, 0x87, 0xa1, 0x52, 0x9e, 0xec,
	0xf9, 0xfb, 0xdb, 0xd9, 0x99, 0xd9, 0x19, 0x28, 0x05, 0x7e, 0xd4, 0x5a, 0x84, 0x41, 0x1c, 0x34,
	0xff, 0xd5, 0xa0, 0xec, 0xd0, 0x70, 0x39, 0x9b, 0xd0, 0xf1, 0x6a, 0x41, 0x91, 0x09, 0x45, 0x8f,
	0x90, 0x90, 0x46, 0x91, 0xa9, 0x35, 0xb4, 0x27, 0x25, 0x9c, 0x90, 0xe8, 0x19, 0x14, 0x5e, 0xcf,
	0xe8, 0x9c, 0x44, 0x66, 0xae, 0x91, 0x7f, 0x52, 0x6e, 0x7f, 0xd8, 0x52, 0xec, 0xd4, 0xff, 0x6f,
	0x99, 0x16, 0x96, 0xca, 0xe8, 0x06, 0xf4, 0x78, 0xb5, 0xa0, 0x91, 0x99, 0x3f, 0xc6, 0x4a, 0xe8,
	0x22, 0x0b, 0x4e, 0x16, 0x61, 0xb0, 0x9c, 0x11, 0x1a, 0x9a, 0x0f, 0xf9, 0x31, 0x52, 0xda, 0xfa,
	0x02, 0x8c, 0x6d, 0x33, 0x64, 0x40, 0xfe, 0x8e, 0xae, 0xe4, 0x89, 0xd9, 0x2f, 0xaa, 0x83, 0xbe,
	0xf4, 0xe6, 0x7f, 0x52, 0x33, 0xc7, 0x79, 0x82, 0x68, 0xfe, 0xa5, 0x41, 0x01, 0xd3, 0x49, 0x10,
	0x12, 0xa6, 0xf0, 0x7a, 0xee, 0x4d, 0x45, 0x98, 0x3a, 0x16, 0x04, 0x0b, 0x3f, 0x12, 0xce, 0xa5,
	0x61, 0x42, 0xa2, 0x4b, 0x28, 0x84, 0x74, 0x4a, 0xdf, 0x2e, 0xcc, 0x3c, 0x17, 0x48, 0x0a, 0x7d,
	0x02, 0x7a, 0x14, 0x7b, 0x31, 0xe5, 0xe7, 0xac, 0xb4, 0x6b, 0x2d, 0xe1, 0x5f, 0x7e, 0x1c, 0x26,
	0xc2, 0x42, 0x63, 0x23, 0x2a, 0x7d, 0x33, 0xaa, 0xe6, 0x33, 0x28, 0x2b, 0x16, 0xa8, 0x06, 0x55,
	0x6c, 0x77, 0x47, 0xb8, 0xe7, 0x0e, 0x86, 0x9d, 0xee, 0x78, 0x70, 0x6b, 0x1b, 0x0f, 0xd0, 0x39,
	0x9c, 0x49, 0xa6, 0x64, 0x69, 0xcd, 0xbf, 0x35, 0x28, 0xf7, 0x9d, 0xa7, 0xdd, 0x80, 0xd0, 0x9e,
	0x17, 0x7b, 0xe8, 0x0a, 0x4e, 0xa6, 0xd1, 0x53, 0x77, 0x12, 0x10, 0x9a, 0xe4, 0x6f, 0x1a, 0x71,
	0x31, 0x13, 0x05, 0x6f, 0x7c, 0x1a, 0xba, 0x33, 0x92, 0xc4, 0xc6, 0xe9, 0x01, 0x41, 0x8f, 0xa1,
	0x18, 0x72, 0xf0, 0x24, 0x4b, 0x45, 0x79, 0x7c, 0x9c, 0xf0, 0xd1, 0xf5, 0x66, 0x98, 0x57, 0x2d,
	0x05, 0x35, 0xf9, 0x57, 0x83, 0x6d, 0x7e, 0x0f, 0xa7, 0x2a, 0x1b, 0x19, 0x82, 0x1e, 0xf5, 0x6c,
	0x77, 0x38, 0x1a, 0xb2, 0x70, 0xea, 0x60, 0x24, 0x9c, 0x34, 0x48, 0x0d, 0x21, 0xa8, 0x24, 0x5c,
	0xc9, 0xcb, 0x35, 0xff, 0xa9, 0xc2, 0x95, 0x43, 0x7d, 0x32, 0x1a, 0x3a, 0xe3, 0xd0, 0xf3, 0x23,
	0x6f, 0x12, 0xcf, 0x02, 0xff, 0xa5, 0xb7, 0x9a, 0x07, 0x1e, 0x41, 0x3f, 0x82, 0x11, 0xaf, 0xb9,
	0x2e, 0xab, 0x20, 0x1e, 0x7b, 0xa5, 0xfd, 0x69, 0x6b, 0xaf, 0x55, 0x6b, 0x93, 0xcb, 0x4a, 0x09,
	0x57, 0xe3, 0x4d, 0x06, 0xa2, 0x70, 0x1e, 0xd2, 0xe9, 0x2c, 0x8a, 0x69, 0xe8, 0xa6, 0xd7, 0xca,
	0xee, 0xae, 0xdc, 0xfe, 0x3c, 0xc3, 0x35, 0x96, 0x36, 0x32, 0x7e, 0x45, 0x83, 0xdd, 0x16, 0xae,
	0x26, 0x3e, 0xfb, 0x32, 0x33, 0x77, 0x50, 0x23, 0x74, 0x17, 0x28, 0xcf, 0x81, 0x9e, 0x67, 0x00,
	0xf5, 0x52, 0xab, 0x3d, 0x50, 0xe7, 0x6b, 0xbf, 0x09, 0x18, 0x06, 0xf0, 0x08, 0x71, 0x45, 0x5e,
	0x79, 0x36, 0xcb, 0xed, 0x9b, 0x0c, 0x8c, 0x0e, 0x21, 0xa2, 0x16, 0xb6, 0x7d, 0x97, 0xbc, 0x44,
	0x82, 0x7e, 0x81, 0xb3, 0x90, 0xfe, 0x1e, 0x2c, 0x69, 0xe2, 0x56, 0xe7, 0x6e, 0x3f, 0xcb, 0xbc,
	0x23, 0xa6, 0x7f, 0xbf, 0xe7, 0xd3, 0x50, 0x11, 0xa2, 0x3f, 0xe0, 0x22, 0xbd, 0x1b, 0xd9, 0x8c,
	0x22, 0xc7, 0x05, 0x0e, 0xf2, 0xe2, 0x88, 0x44, 0x28, 0xef, 0xc5, 0x36, 0x56, 0x2d, 0xdc, 0xd5,
	0x41, 0x6f, 0xe0, 0x91, 0x92, 0x90, 0x0d, 0xd0, 0x22, 0x07, 0xfd, 0xea, 0xa8, 0xa4, 0x64, 0xc0,
	0x5e, 0x90, 0xfb, 0xb4, 0x50, 0x00, 0x17, 0x93, 0xdf, 0x3c, 0x7f, 0x4a, 0xd3, 0x2a, 0x70, 0x45,
	0xd7, 0x9d, 0x70, 0xd8, 0x2f, 0x33, 0x60, 0xbb, 0xdc, 0x4e, 0x6d, 0xb9, 0x6d, 0x4c, 0x24, 0x5c,
	0xcb, 0x42, 0x10, 0x5d, 0x79, 0x07, 0x35, 0x09, 0x28, 0x32, 0x27, 0xe1, 0x4a, 0x07, 0x4b, 0x4f,
	0xc0, 0x29, 0x4f, 0xd6, 0x4e, 0xe9, 0x4d, 0xb6, 0x35, 0xac, 0xe7, 0xf0, 0x51, 0x76, 0x6b, 0x64,
	0x3c, 0x5f, 0xd6, 0x0b, 0x68, 0x1c, 0x2a, 0xf7, 0x2c, 0xf3, 0x5f, 0xa1, 0xbe, 0x2e, 0x36, 0xc5,
	0xe4, 0x3d, 0x8d, 0x01, 0xeb, 0x1d, 0x98, 0xfb, 0x3a, 0x25, 0xeb, 0x51, 0xee, 0x33, 0x77, 0xbc,
	0x65, 0xc4, 0xb3, 0x72, 0x9d, 0x59, 0xcd, 0xbb, 0xe7, 0xc7, 0xd2, 0xdc, 0x1a, 0xc2, 0x07, 0x19,
	0x2d, 0x95, 0x75, 0x84, 0x3a, 0xe8, 0x33, 0x9f, 0xd0, 0xb7, 0xfc, 0x04, 0x67, 0x58, 0x10, 0x56,
	0x00, 0xcd, 0xc3, 0xdd, 0x93, 0xb1, 0x2d, 0x5c, 0xc3, 0xe9, 0x46, 0xdf, 0x88, 0xf0, 0x4e, 0xd5,
	0x89, 0x8f, 0xcb, 0xd1, 0x9a, 0xb0, 0xbe, 0x86, 0x8f, 0x8f, 0xe9, 0x9c, 0xfd, 0x90, 0x56, 0x00,
	0x8f, 0x0f, 0x36, 0x41, 0xd6, 0x45, 0xa4, 0x23, 0x2e, 0x77, 0xdc, 0x88, 0xb3, 0xde, 0x41, 0xe3,
	0x50, 0x1b, 0xfc, 0xef, 0x8b, 0x5f, 0xef, 0x13, 0xf9, 0x43, 0xfb, 0x04, 0xdb, 0x66, 0xd0, 0xee,
	0x18, 0x63, 0x73, 0x15, 0xdb, 0xfd, 0x81, 0x33, 0xb6, 0xb1, 0x2b, 0x47, 0xa9, 0xf1, 0x00, 0x5d,
	0x02, 0xea, 0xd9, 0x3b, 0x7c, 0x0d, 0x55, 0x00, 0x3a, 0xbd, 0x9e, 0x2b, 0x16, 0x0b, 0x23, 0x27,
	0x96, 0x8c, 0x1f, 0x46, 0xb7, 0x76, 0xc2, 0xca, 0x23, 0x13, 0xea, 0xa9, 0xa1, 0x63, 0xe3, 0xdb,
	0x41, 0xd7, 0x1e, 0xff, 0xf4, 0xd2, 0x36, 0x1e, 0x22, 0x0b, 0x2e, 0x15, 0xa7, 0xaa, 0x4c, 0x67,
	0x56, 0xdd, 0xef, 0x3a, 0xc3, 0xbe, 0x9d, 0x80, 0xb9, 0xce, 0xb8, 0x33, 0xb6, 0x8d, 0x02, 0x7a,
	0x04, 0x35, 0x29, 0x91, 0xeb, 0x8c, 0x10, 0x14, 0xbf, 0x29, 0xfd, 0x5c, 0x0c, 0xfc, 0xc8, 0x5d,
	0xbc, 0x6a, 0xbf, 0x2a, 0xf0, 0xf5, 0xf4, 0xe6, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x66, 0x9b,
	0x75, 0xbb, 0xab, 0x0a, 0x00, 0x00,
}
